const image = (name) => `/assets/kaleb-aguiar/${name}`;
const linkImage = (name) => image(`linkpage-curated/${name}`);

export const clientConfig = {
  brand: "Atelier Kaleb Aguiar",
  descriptor: "Designer de moda",
  handle: "@kaleb_aguiar",
  instagramUrl: "https://www.instagram.com/kaleb_aguiar/",
  facebookUrl: "https://www.facebook.com/p/Kaleb-Aguiar-100063493009146/",
  whatsappUrl: "https://wa.me/5592993509850",
  fallbackContactUrl: "https://wa.me/5592993509850",
  phoneDisplay: "+55 92 99350-9850",
  contactMode: "whatsapp",
  contactNote: "Atendimento inicial pelo WhatsApp. Voce pode tirar duvidas e visitar o atelie sem compromisso antes de decidir.",
  city: "Manaus, AM",
  address: "Rua Rio Purus, 1078 - Vieiralves, Manaus - AM",
  addressShort: "Rua Rio Purus, 1078 - Vieiralves",
  promise: "Reserve o vestido da sua grande entrada.",
  positioning: "Aluguel exclusivo para debutantes, madrinhas, moda festa, formatura, noivas, exclusivos e Miss em Manaus. Conheca os modelos, tire duvidas e visite o atelie sem compromisso antes de decidir.",
  proof: ["Visita sem compromisso", "Atelie em Vieiralves", "Debutantes | Moda festa | Miss"],
  assets: {
    logo: image("kaleb-logo.jpeg"),
    hero: image("hero-debutante-roxo-escadaria.png"),
    heroMobileBoi: image("mobile-bg-boi-final.png"),
    heroMobileNicole: image("mobile-bg-nicole-red-final.png"),
    green: image("vestido-verde-plumas-corredor.png"),
    red: image("vestido-vermelho-fenda.png"),
    blue: image("figurino-azul-palco.png"),
    sash: image("vestido-verde-faixa.png"),
    lilac: image("vestido-lilas-baloes.png"),
    silver: image("vestido-prata-noite.png"),
  },
  links: {
    maps: "https://www.google.com/maps/search/?api=1&query=Rua%20Rio%20Purus%2C%201078%20-%20Vieiralves%2C%20Manaus%20-%20AM",
    uber: "https://m.uber.com/ul/?action=setPickup&pickup=my_location&dropoff[latitude]=-3.1071200&dropoff[longitude]=-60.0211834&dropoff[nickname]=Atelier%20Kaleb%20Aguiar&dropoff[formatted_address]=Rua%20Rio%20Purus%2C%201078%20-%20Vieiralves%2C%20Manaus%20-%20AM",
  },
  categories: [
    {
      id: "debutante",
      label: "Debutantes",
      eyebrow: "15 anos",
      title: "Ver vestidos de debutantes",
      body: "Vestidos com volume, brilho e presenca para uma entrada marcante.",
      image: image("hero-debutante-roxo-escadaria.png"),
      accent: "var(--rose)",
    },
    {
      id: "madrinha",
      label: "Madrinha e Moda Festa",
      eyebrow: "Eventos e casamentos",
      title: "Ver madrinha e moda festa",
      body: "Modelos elegantes para casamento, recepcao, fotos e eventos especiais.",
      image: image("vestido-verde-plumas-corredor.png"),
      accent: "var(--jade)",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Colacao e baile",
      title: "Ver vestidos de formatura",
      body: "Bordados, fendas e silhuetas de impacto para celebrar sua conquista.",
      image: image("vestido-vermelho-fenda.png"),
      accent: "var(--ruby)",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimonia",
      title: "Consultar vestidos de noiva",
      body: "Opcoes para quem procura uma peca delicada, marcante e fotografavel.",
      image: image("vestido-prata-noite.png"),
      accent: "var(--ivory)",
    },
    {
      id: "palco",
      label: "Exclusivos",
      eyebrow: "Modelos especiais",
      title: "Ver modelos exclusivos",
      body: "Pecas de impacto para ensaios, eventos, palco e producoes especiais.",
      image: image("figurino-azul-palco.png"),
      accent: "var(--sapphire)",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      title: "Ver vestidos para Miss",
      body: "Pecas de destaque para concurso, apresentacao, palco e momentos de presenca.",
      image: image("vestido-lilas-baloes.png"),
      accent: "var(--violet)",
    },
  ],
  linkpageCategories: [
    {
      id: "debutante",
      label: "Debutantes",
      eyebrow: "15 anos",
      title: "Ver vestidos de debutantes",
      body: "Vestidos com volume, brilho e presenca para uma entrada marcante.",
      image: linkImage("cover-debutante-rosa-palco.webp"),
      accent: "var(--rose)",
      imagePosition: "50% 18%",
      mobilePosition: "52% 12%",
      tilePosition: "50% 16%",
    },
    {
      id: "madrinha",
      label: "Madrinha e Moda Festa",
      eyebrow: "Eventos e casamentos",
      title: "Ver madrinha e moda festa",
      body: "Modelos elegantes para casamento, recepcao, fotos e eventos especiais.",
      image: linkImage("cover-madrinha-rosa-festa.webp"),
      accent: "var(--jade)",
      imagePosition: "50% 10%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 14%",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Colacao e baile",
      title: "Ver vestidos de formatura",
      body: "Bordados, fendas e silhuetas de impacto para celebrar sua conquista.",
      image: linkImage("cover-formatura-verde-evento.webp"),
      accent: "var(--ruby)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 12%",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimonia",
      title: "Consultar vestidos de noiva",
      body: "Opcoes para quem procura uma peca delicada, marcante e fotografavel.",
      image: linkImage("cover-noiva-branco-noite.webp"),
      accent: "var(--ivory)",
      imagePosition: "58% 18%",
      mobilePosition: "58% 12%",
      tilePosition: "58% 16%",
    },
    {
      id: "palco",
      label: "Exclusivos",
      eyebrow: "Modelos especiais",
      title: "Ver modelos exclusivos",
      body: "Pecas de impacto para ensaios, eventos, palco e producoes especiais.",
      image: linkImage("cover-exclusivo-vermelho-flor.webp"),
      accent: "var(--sapphire)",
      imagePosition: "50% 8%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 12%",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      title: "Ver vestidos para Miss",
      body: "Pecas de destaque para concurso, apresentacao, palco e momentos de presenca.",
      image: linkImage("cover-miss-prata-coroa.webp"),
      accent: "var(--violet)",
      imagePosition: "50% 8%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 10%",
    },
  ],
  process: [
    ["01", "Diga sua data", "Informe o evento, horario e tipo de vestido que procura."],
    ["02", "Escolha o estilo", "Envie referencias de cor, brilho, volume e caimento."],
    ["03", "Visite sem compromisso", "O atelie orienta opcoes antes da sua decisao."],
    ["04", "Reserve o modelo", "Gostou do vestido? Saia com a data encaminhada."],
  ],
};

export function buildReservationUrl(context = "") {
  const message = context
    ? `Ola, Atelier Kaleb Aguiar. Vim pelo site e quero conhecer os vestidos sem compromisso. Tenho interesse em: ${context}.`
    : "Ola, Atelier Kaleb Aguiar. Vim pelo site e quero conhecer os vestidos sem compromisso.";
  return `${clientConfig.whatsappUrl}?text=${encodeURIComponent(message)}`;
}
