const image = (name) => `/assets/kaleb-aguiar/${name}`;
const linkImage = (name) => image(`linkpage-curated/${name}`);
const dressImage = (path) => `/assets/Kaleb-aguiar-1/${path}`;
const makeGallery = (...paths) => paths.map(dressImage);

const dressBackgroundVariants = {
  "debutante-boneca": "portrait-tight",
  "noiva-bride-reel": "portrait-tight",
  "miss-beleza-brasil": "portrait-tight",
  "madrinha-kaleb-aguiar": "square-scene",
  "debutante-dress": "square-scene",
  "debutante-rosa-classico": "square-scene",
  "exclusivo-detalhe-autoral": "detail-wash",
};

const dressBackgroundPositions = {
  "madrinha-kaleb-aguiar": "50% 48%",
  "debutante-rosa-classico": "50% 48%",
  "miss-dudezzle-gala": "50% 45%",
  "exclusivo-detalhe-autoral": "50% 42%",
};

const dressBackgroundMobilePositions = {
  "madrinha-kaleb-aguiar": "50% 48%",
  "debutante-rosa-classico": "50% 46%",
  "miss-dudezzle-gala": "50% 42%",
  "exclusivo-detalhe-autoral": "50% 40%",
};

const applyDressBackgroundProfile = (item) => ({
  ...item,
  backgroundVariant: dressBackgroundVariants[item.id] || "portrait-full",
  backgroundPosition: dressBackgroundPositions[item.id] || item.imagePosition || "50% 16%",
  backgroundMobilePosition: dressBackgroundMobilePositions[item.id] || item.mobilePosition || item.imagePosition || "50% 14%",
});

export const clientConfig = {
  brand: "Atelier Kaleb Aguiar",
  descriptor: "Designer de moda",
  handle: "@kaleb_aguiar",
  instagramUrl: "https://www.instagram.com/kaleb_aguiar/",
  facebookUrl: "https://www.facebook.com/p/Kaleb-Aguiar-100063493009146/",
  whatsappUrl: "https://wa.me/5592993509850",
  fallbackContactUrl: "https://wa.me/5592993509850",
  phoneDisplay: "+55 92 99350-9850",
  contactMode: "whatsapp",
  contactNote: "Envie sua data, ocasião e estilo para o ateliê orientar modelos antes da visita.",
  city: "Manaus, AM",
  address: "Rua Rio Purus 1078 - Vieiralves, Manaus - AM",
  addressShort: "Rua Rio Purus 1078 - Vieiralves",
  promise: "Reserve o vestido da sua grande entrada.",
  positioning: "Vestidos reais para debutantes, madrinhas, formandas, noivas, Miss e produções autorais em Manaus. Veja o acervo e fale com o ateliê antes da visita.",
  proof: ["15 anos", "Madrinhas", "Moda festa", "Formatura", "Noivas", "Miss", "Autorais"],
  assets: {
    logo: image("kaleb-logo.jpeg"),
    hero: image("background-herosection-new/debutante-1.jpeg"),
    heroSlides: [
      {
        src: image("background-herosection-new/debutante-1.jpeg"),
        position: "center center",
        mobilePosition: "98% center",
        mobilePanelLeft: "15%",
        scaleStart: "1",
        scaleEnd: "1.02",
        shiftXEnd: "-0.15%",
        shiftYEnd: "-0.08%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.02",
        mobileShiftYStart: "0",
        mobileShiftYEnd: "-4px",
        frameWidth: "100%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "100%",
        shortFrameBottom: "0px",
      },
      {
        src: image("background-herosection-new/debutante-2.jpeg"),
        position: "center center",
        mobilePosition: "92% center",
        mobilePanelLeft: "24%",
        scaleStart: "1",
        scaleEnd: "1.02",
        shiftXEnd: "-0.15%",
        shiftYEnd: "-0.08%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.02",
        mobileShiftYStart: "0",
        mobileShiftYEnd: "-4px",
        frameWidth: "100%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "100%",
        shortFrameBottom: "0px",
      },
      {
        src: image("background-herosection-new/debutante-3.jpeg"),
        position: "center center",
        mobilePosition: "88% center",
        mobilePanelLeft: "34%",
        scaleStart: "1",
        scaleEnd: "1.02",
        shiftXEnd: "-0.15%",
        shiftYEnd: "-0.08%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.02",
        mobileShiftYStart: "0",
        mobileShiftYEnd: "-4px",
        frameWidth: "100%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "100%",
        shortFrameBottom: "0px",
      },
      {
        src: image("background-herosection-new/debutante-4.jpeg"),
        position: "center center",
        mobilePosition: "100% center",
        mobilePanelLeft: "-6%",
        scaleStart: "1",
        scaleEnd: "1.02",
        shiftXEnd: "-0.15%",
        shiftYEnd: "-0.08%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.02",
        mobileShiftYStart: "0",
        mobileShiftYEnd: "-4px",
        frameWidth: "100%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "100%",
        shortFrameBottom: "0px",
      },
    ],
    heroMobileBoi: image("mobile-bg-boi-final.png"),
    heroMobileNicole: image("mobile-bg-nicole-red-final.png"),
    green: image("vestido-verde-plumas-corredor.png"),
    red: image("vestido-vermelho-fenda.png"),
    blue: image("figurino-azul-palco.png"),
    sash: image("vestido-verde-faixa.png"),
    lilac: image("vestido-lilas-baloes.png"),
    reserveHorizontal: dressImage("debutantes-03 (1).jpg"),
    silver: image("vestido-prata-noite.png"),
  },
  links: {
    maps: "https://www.google.com/maps/search/?api=1&query=Rua%20Rio%20Purus%201078%2C%20Vieiralves%2C%20Manaus%20-%20AM",
    uber: "https://m.uber.com/looking?pickup=my_location&drop[0]=%7B%22addressLine1%22%3A%22Rua%20Rio%20Purus%201078%20-%20Vieiralves%2C%20Manaus%20-%20AM%22%2C%22addressLine2%22%3A%22Rua%20Rio%20Purus%201078%20-%20Vieiralves%2C%20Manaus%20-%20AM%22%7D",
  },
  categories: [
    {
      id: "debutante",
      label: "Debutantes",
      eyebrow: "15 anos",
      title: "Ver vestidos de 15 anos",
      body: "Volume, brilho e presença para uma entrada marcante.",
      image: image("hero-debutante-roxo-escadaria.png"),
      accent: "var(--rose)",
    },
    {
      id: "madrinha",
      label: "Madrinha e Moda Festa",
      eyebrow: "Eventos e casamentos",
      title: "Ver moda festa e madrinhas",
      body: "Cores, caimentos e looks para casamento, recepção e noite especial.",
      image: linkImage("cover-madrinha-rosa-festa.webp"),
      accent: "var(--jade)",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Colacao e baile",
      title: "Ver looks de formatura",
      body: "Bordados, fendas e silhuetas de impacto para celebrar sua conquista.",
      image: image("vestido-vermelho-fenda.png"),
      accent: "var(--ruby)",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimônia",
      title: "Consultar referências de noiva",
      body: "Modelos delicados para avaliar proporção, cerimônia e foto.",
      image: image("vestido-prata-noite.png"),
      accent: "var(--ivory)",
    },
    {
      id: "palco",
      label: "Exclusivos",
      eyebrow: "Modelos especiais",
      title: "Ver peças autorais",
      body: "Criações de impacto para festa, palco, ensaio e produção especial.",
      image: image("figurino-azul-palco.png"),
      accent: "var(--sapphire)",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      title: "Ver looks de palco e faixa",
      body: "Gala, postura e brilho para concursos e apresentações.",
      image: image("vestido-lilas-baloes.png"),
      accent: "var(--violet)",
    },
  ],
  linkpageCategories: [
    {
      id: "debutante",
      label: "Debutantes",
      eyebrow: "15 anos",
      title: "Ver vestidos de 15 anos",
      body: "Volume, brilho e presença para uma entrada marcante.",
      image: linkImage("cover-debutante-rosa-palco.webp"),
      accent: "var(--rose)",
      imagePosition: "50% 18%",
      mobilePosition: "52% 12%",
      tilePosition: "50% 16%",
    },
    {
      id: "madrinha",
      label: "Madrinha e Moda Festa",
      eyebrow: "Eventos e casamentos",
      title: "Ver moda festa e madrinhas",
      body: "Cores, caimentos e looks para casamento, recepção e noite especial.",
      image: linkImage("cover-madrinha-rosa-festa.webp"),
      accent: "var(--jade)",
      imagePosition: "50% 10%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 14%",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Colacao e baile",
      title: "Ver looks de formatura",
      body: "Bordados, fendas e silhuetas de impacto para celebrar sua conquista.",
      image: linkImage("cover-formatura-verde-evento.webp"),
      accent: "var(--ruby)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 12%",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimônia",
      title: "Consultar referências de noiva",
      body: "Modelos delicados para avaliar proporção, cerimônia e foto.",
      image: linkImage("cover-noiva-branco-noite.webp"),
      accent: "var(--ivory)",
      imagePosition: "58% 18%",
      mobilePosition: "58% 12%",
      tilePosition: "58% 16%",
    },
    {
      id: "palco",
      label: "Exclusivos",
      eyebrow: "Modelos especiais",
      title: "Ver peças autorais",
      body: "Criações de impacto para festa, palco, ensaio e produção especial.",
      image: linkImage("cover-exclusivo-vermelho-flor.webp"),
      accent: "var(--sapphire)",
      imagePosition: "50% 8%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 12%",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      title: "Ver looks de palco e faixa",
      body: "Gala, postura e brilho para concursos e apresentações.",
      image: linkImage("cover-miss-prata-coroa.webp"),
      accent: "var(--violet)",
      imagePosition: "50% 8%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 10%",
    },
  ],
  dressCollections: [
    {
      id: "madrinha-moda-festa",
      label: "Madrinha e Moda Festa",
      eyebrow: "Casamentos e eventos",
      headline: "Moda festa com caimento de ateliê.",
      body: "Compare cor, caimento e presença em fotos reais antes de chamar o ateliê.",
      accent: "var(--jade)",
    },
    {
      id: "debutantes",
      label: "Debutantes",
      eyebrow: "15 anos",
      headline: "Entrada de 15 anos em cena.",
      body: "Volume, brilho e romantismo para escolher uma direção antes da prova.",
      accent: "var(--rose)",
      albumCover: dressImage("debutantes (2).jpg"),
      featuredItemId: "debutantes-acervo-completo",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Baile e colação",
      headline: "Gala para a noite da conquista.",
      body: "Looks de baile e colação para avaliar presença, foto e acabamento de festa.",
      accent: "var(--ruby)",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimônia",
      headline: "Noiva com delicadeza, proporção e cerimônia.",
      body: "Fotos reais para observar volume, caimento e imagem antes do atendimento.",
      accent: "var(--ivory)",
      albumCover: dressImage("noiva/05-p-dqnvidwefud/slide-01.jpg"),
      featuredItemId: "noiva-laila",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      headline: "Palco, faixa e autoridade.",
      body: "Vestidos de concurso para comparar brilho, postura e presença sob luz.",
      accent: "var(--violet)",
    },
    {
      id: "exclusivos",
      label: "Exclusivos",
      eyebrow: "Autoral e cena",
      headline: "Peças autorais para palco, festa e grandes entradas.",
      body: "Criações de ateliê com textura, repertório e presença visual.",
      accent: "var(--gold)",
      albumCover: dressImage("03-mylennaaguiar-p-dwz8ogtdykq/slide-01.jpg"),
      featuredItemId: "exclusivo-flor-matizada",
    },
  ],
  dressItems: [
    {
      id: "madrinha-yari-angel",
      collectionId: "madrinha-moda-festa",
      title: "Rose de gala",
      eyebrow: "Madrinha",
      shortDescription: "Rose para casamento, recepção e noite especial, com suavidade e presença em foto.",
      detailDescription: "Rose para casamento, recepção e noite especial, com suavidade e presença em foto.",
      idealFor: ["Casamento", "Madrinha", "Recepcao", "Fotos oficiais"],
      visualDetails: ["Tom rosé elegante", "Caimento de gala", "Presença suave", "Boa leitura em foto"],
      gallery: makeGallery("04-madrinha-moda-festa-yari-angel-467-likes-2-fotos/debutantes (1).jpg", "04-madrinha-moda-festa-yari-angel-467-likes-2-fotos/debutantes (2).jpg"),
      backgroundImage: dressImage("04-madrinha-moda-festa-yari-angel-467-likes-2-fotos/debutantes (1).jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--jade)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 14%",
      whatsappContext: "madrinha e moda festa, look rose",
    },
    {
      id: "madrinha-kaleb-aguiar",
      collectionId: "madrinha-moda-festa",
      title: "Blush cerimonial",
      eyebrow: "Moda festa",
      shortDescription: "Blush elegante para indicar cor, ocasião e data ao ateliê.",
      detailDescription: "Blush elegante para indicar cor, ocasião e data ao ateliê.",
      idealFor: ["Casamento civil", "Recepcao", "Convidada premium", "Evento noturno"],
      visualDetails: ["Tom blush", "Elegância limpa", "Silhueta fotografável", "Acabamento de festa"],
      gallery: makeGallery("05-madrinha-moda-festa-kaleb-aguiar-289-likes-2/madrinha-moda-festa-trabalho-05-foto-01-DB9P7e-PSbg.jpg", "05-madrinha-moda-festa-kaleb-aguiar-289-likes-2/madrinha-moda-festa-trabalho-05-foto-02-DB9P7e-PSbg.jpg"),
      backgroundImage: dressImage("05-madrinha-moda-festa-kaleb-aguiar-289-likes-2/madrinha-moda-festa-trabalho-05-foto-01-DB9P7e-PSbg.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--jade)",
      imagePosition: "50% 50%",
      mobilePosition: "50% 50%",
      whatsappContext: "madrinha e moda festa, look blush",
    },
    {
      id: "madrinha-verde-plumas",
      collectionId: "madrinha-moda-festa",
      title: "Verde festa",
      eyebrow: "Moda festa",
      shortDescription: "Verde de impacto para avaliar movimento, brilho e leitura de corpo.",
      detailDescription: "Verde de impacto para avaliar movimento, brilho e leitura de corpo.",
      idealFor: ["Madrinha", "Evento noturno", "Recepcao", "Fotos de entrada"],
      visualDetails: ["Verde de presença", "Brilho de festa", "Movimento elegante", "Leitura de corpo"],
      gallery: [linkImage("cover-formatura-verde-evento.webp")],
      backgroundImage: linkImage("cover-formatura-verde-evento.webp"),
      proof: "Foto real do acervo",
      accent: "var(--jade)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 14%",
      whatsappContext: "madrinha e moda festa, vestido verde",
    },
    {
      id: "debutante-boneca",
      collectionId: "debutantes",
      title: "Princesa azul",
      eyebrow: "15 anos",
      shortDescription: "Volume de 15 anos com delicadeza, entrada e presença de festa.",
      detailDescription: "Volume de 15 anos com delicadeza, entrada e presença de festa.",
      idealFor: ["15 anos", "Entrada principal", "Ensaio fotografico", "Festa classica"],
      visualDetails: ["Volume de debutante", "Leitura romântica", "Presença de palco", "Foto de impacto"],
      gallery: makeGallery("debutantes-01/slide-01.jpg", "debutantes-01/slide-02.jpg"),
      backgroundImage: dressImage("debutantes-01/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--rose)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "debutante boneca",
    },
    {
      id: "debutante-dress",
      collectionId: "debutantes",
      title: "Sonho de 15 anos",
      eyebrow: "15 anos",
      shortDescription: "Referência de debutante para conversar sobre volume, cor e entrada.",
      detailDescription: "Referência de debutante para conversar sobre volume, cor e entrada.",
      idealFor: ["15 anos", "Fotos antes da festa", "Entrada", "Recepcao"],
      visualDetails: ["Estetica delicada", "Efeito princesa", "Linha romantica", "Boa leitura vertical"],
      gallery: makeGallery("debutantes-01 (3)/slide-01.jpg"),
      backgroundImage: dressImage("debutantes-01 (3)/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--rose)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de debutante dress",
    },
    {
      id: "debutante-rosa-classico",
      collectionId: "debutantes",
      title: "Rosa clássico",
      eyebrow: "15 anos",
      shortDescription: "Rosa de festa para comparar volume, postura e impacto visual.",
      detailDescription: "Rosa de festa para comparar volume, postura e impacto visual.",
      idealFor: ["15 anos", "Festa classica", "Baile", "Fotos de familia"],
      visualDetails: ["Rosa debutante", "Volume presente", "Acabamento cenico", "Movimento de festa"],
      gallery: makeGallery("debutantes-01 (4)/slide-01.jpg", "debutantes-01 (4)/slide-02.jpg"),
      backgroundImage: dressImage("debutantes-01 (4)/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--rose)",
      imagePosition: "50% 45%",
      mobilePosition: "50% 42%",
      whatsappContext: "vestido de debutante rosa clássico",
    },
    {
      id: "debutante-ensaio",
      collectionId: "debutantes",
      title: "Editorial 15 anos",
      eyebrow: "Ensaio",
      shortDescription: "Fotos de 15 anos para escolher brilho, cor e presença antes da visita.",
      detailDescription: "Fotos de 15 anos para escolher brilho, cor e presença antes da visita.",
      idealFor: ["Ensaio fotografico", "15 anos", "Entrada", "Editorial familiar"],
      visualDetails: ["Imagem de debutante", "Volume fotografável", "Brilho de festa", "Cena de memória"],
      gallery: [
        image("vestido-lilas-baloes.png"),
        image("hero-debutante-roxo-escadaria.png"),
        linkImage("cover-debutante-rosa-palco.webp"),
        dressImage("debutantes-01 (2)/slide-01.jpg"),
      ],
      backgroundImage: image("vestido-lilas-baloes.png"),
      proof: "4 fotos reais de 15 anos",
      accent: "var(--rose)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "referencias de debutante para ensaio de 15 anos",
    },
    {
      id: "formatura-medicina",
      collectionId: "formatura",
      title: "Gala da conquista",
      eyebrow: "Baile",
      shortDescription: "Gala de formatura para avaliar foto, acabamento e presença.",
      detailDescription: "Gala de formatura para avaliar foto, acabamento e presença.",
      idealFor: ["Baile de formatura", "Medicina", "Colacao", "Fotos oficiais"],
      visualDetails: ["Gala de formatura", "Impacto em foto", "Linha celebrativa", "Acabamento nobre"],
      gallery: makeGallery("formatura02/slide-01.jpg", "formatura02/slide-02.jpg"),
      backgroundImage: dressImage("formatura02/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ruby)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de formatura gala da conquista",
    },
    {
      id: "formatura-vermelho-gala",
      collectionId: "formatura",
      title: "Vermelho de gala",
      eyebrow: "Gala",
      shortDescription: "Vermelho marcante para formanda que quer presença forte no baile.",
      detailDescription: "Vermelho marcante para formanda que quer presença forte no baile.",
      idealFor: ["Baile", "Formanda", "Evento noturno", "Fotos de conquista"],
      visualDetails: ["Vermelho intenso", "Presença de gala", "Silhueta marcante", "Efeito noturno"],
      gallery: makeGallery("formatura03/slide-01.jpg", "formatura03/slide-02.jpg"),
      backgroundImage: dressImage("formatura03/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ruby)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido vermelho de formatura",
    },
    {
      id: "formatura-alta-costura",
      collectionId: "formatura",
      title: "Gala de ateliê",
      eyebrow: "Exclusivo",
      shortDescription: "Look de gala com acabamento de ateliê e direção menos comum.",
      detailDescription: "Look de gala com acabamento de ateliê e direção menos comum.",
      idealFor: ["Formatura", "Gala", "Cliente especial", "Evento formal"],
      visualDetails: ["Modelo exclusivo", "Leitura sofisticada", "Acabamento de ateliê", "Presença editorial"],
      gallery: makeGallery("fomatura/slide-01.jpg"),
      backgroundImage: dressImage("fomatura/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ruby)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 12%",
      whatsappContext: "formatura alta costura",
    },
    {
      id: "noiva-vestido-classico",
      collectionId: "noiva",
      title: "Noiva classica",
      eyebrow: "Noiva",
      shortDescription: "Noiva delicada para observar proporção, cerimônia e imagem.",
      detailDescription: "Noiva delicada para observar proporção, cerimônia e imagem.",
      idealFor: ["Cerimônia", "Noiva", "Fotos do casal", "Casamento clássico"],
      visualDetails: ["Branco delicado", "Leitura de cerimônia", "Foto limpa", "Presença romântica"],
      gallery: makeGallery("noiva/01-p-c0tw3-qosfj/slide-01.jpg"),
      backgroundImage: dressImage("noiva/01-p-c0tw3-qosfj/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ivory)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de noiva clássico",
    },
    {
      id: "noiva-janaina",
      collectionId: "noiva",
      title: "Noiva jardim",
      eyebrow: "Noiva",
      shortDescription: "Delicadeza de noiva para avaliar caimento e cenário de cerimônia.",
      detailDescription: "Delicadeza de noiva para avaliar caimento e cenário de cerimônia.",
      idealFor: ["Cerimônia", "Noiva", "Casamento diurno", "Fotos externas"],
      visualDetails: ["Branco suave", "Caimento delicado", "Elegancia classica", "Imagem limpa"],
      gallery: makeGallery("noiva/02-p-colo74doqs9/slide-01.jpg", "noiva/02-p-colo74doqs9/slide-02.jpg"),
      backgroundImage: dressImage("noiva/02-p-colo74doqs9/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ivory)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 14%",
      whatsappContext: "vestido de noiva jardim",
    },
    {
      id: "noiva-bride-reel",
      collectionId: "noiva",
      title: "Noiva editorial",
      eyebrow: "Noiva",
      shortDescription: "Noiva editorial para avaliar proporção, beleza e presença em foto.",
      detailDescription: "Noiva editorial para avaliar proporção, beleza e presença em foto.",
      idealFor: ["Noiva", "Making of", "Beleza da noiva", "Referência de prova"],
      visualDetails: ["Imagem vertical", "Foco na noiva", "Clima delicado", "Leitura de beleza"],
      gallery: makeGallery("noiva/03-reel-c1m55dnlpvf/slide-01.jpg"),
      backgroundImage: dressImage("noiva/03-reel-c1m55dnlpvf/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ivory)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "referência de noiva editorial",
    },
    {
      id: "noiva-nayara-gabriel",
      collectionId: "noiva",
      title: "Noiva romantica",
      eyebrow: "Casamento",
      shortDescription: "Vestido de casamento para comparar volume, proporção e foto.",
      detailDescription: "Vestido de casamento para comparar volume, proporção e foto.",
      idealFor: ["Casamento", "Cerimônia", "Fotos oficiais", "Entrada da noiva"],
      visualDetails: ["Branco cerimonial", "Volume romântico", "Imagem de casamento", "Acabamento delicado"],
      gallery: makeGallery("noiva/04-p-djsm0qip8yd1jef5-7rvto7shvaf5xs0khevq80/slide-01.jpg", "noiva/04-p-djsm0qip8yd1jef5-7rvto7shvaf5xs0khevq80/slide-02.jpg"),
      backgroundImage: dressImage("noiva/04-p-djsm0qip8yd1jef5-7rvto7shvaf5xs0khevq80/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ivory)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de noiva romantica",
    },
    {
      id: "noiva-laila",
      collectionId: "noiva",
      title: "Noiva delicada",
      eyebrow: "Noiva",
      shortDescription: "Noiva suave, com presença visual e direção clara para atendimento.",
      detailDescription: "Noiva suave, com presença visual e direção clara para atendimento.",
      idealFor: ["Noiva", "Cerimônia", "Ensaio", "Referência de estilo"],
      visualDetails: ["Imagem vertical", "Leitura romântica", "Presença suave", "Detalhe de noiva"],
      gallery: makeGallery("noiva/05-p-dqnvidwefud/slide-01.jpg"),
      backgroundImage: dressImage("noiva/05-p-dqnvidwefud/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ivory)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de noiva delicada",
    },
    {
      id: "miss-dress-faixa",
      collectionId: "miss",
      title: "Gala de faixa",
      eyebrow: "Miss",
      shortDescription: "Look de concurso para avaliar faixa, postura e presença de palco.",
      detailDescription: "Look de concurso para avaliar faixa, postura e presença de palco.",
      idealFor: ["Concurso", "Miss", "Desfile", "Apresentação"],
      visualDetails: ["Postura de palco", "Leitura de faixa", "Gala", "Imagem de autoridade"],
      gallery: makeGallery("miss/01-p-czfnxksufxn/slide-01.jpg", "miss/01-p-czfnxksufxn/slide-02.jpg"),
      backgroundImage: dressImage("miss/01-p-czfnxksufxn/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido para Miss com faixa",
    },
    {
      id: "miss-beleza-brasil",
      collectionId: "miss",
      title: "Gala nacional",
      eyebrow: "Concurso",
      shortDescription: "Gala de concurso com leitura vertical e impacto de passarela.",
      detailDescription: "Gala de concurso com leitura vertical e impacto de passarela.",
      idealFor: ["Miss", "Concurso", "Passarela", "Gala"],
      visualDetails: ["Imagem de passarela", "Presença vertical", "Gala de concurso", "Impacto sob luz"],
      gallery: makeGallery("miss/02-reel-dkacr8wnj1b/slide-01.jpg"),
      backgroundImage: dressImage("miss/02-reel-dkacr8wnj1b/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--violet)",
      imagePosition: "50% 10%",
      mobilePosition: "50% 8%",
      whatsappContext: "vestido de gala nacional para Miss",
    },
    {
      id: "miss-rainha-cupuacu",
      collectionId: "miss",
      title: "Gala rainha regional",
      eyebrow: "Gala",
      shortDescription: "Gala regional com presença cultural, palco e acabamento cênico.",
      detailDescription: "Gala regional com presença cultural, palco e acabamento cênico.",
      idealFor: ["Rainha", "Concurso", "Gala", "Evento cultural"],
      visualDetails: ["Gala amazonense", "Leitura de rainha", "Presença cultural", "Acabamento cênico"],
      gallery: makeGallery("miss/03-p-dowft85jolk/slide-01.jpg", "miss/03-p-dowft85jolk/slide-02.jpg"),
      backgroundImage: dressImage("miss/03-p-dowft85jolk/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de gala Rainha do Cupuacu",
    },
    {
      id: "miss-continente-gala",
      collectionId: "miss",
      title: "Gala continental",
      eyebrow: "Gala",
      shortDescription: "Look de desfile com brilho controlado e presença de longe.",
      detailDescription: "Look de desfile com brilho controlado e presença de longe.",
      idealFor: ["Desfile de gala", "Miss", "Concurso", "Palco"],
      visualDetails: ["Gala formal", "Postura de desfile", "Presença de longe", "Brilho controlado"],
      gallery: makeGallery("miss/04-p-drle-cnday5/slide-01.jpg"),
      backgroundImage: dressImage("miss/04-p-drle-cnday5/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--violet)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido Miss Continente gala",
    },
    {
      id: "miss-amazonas-top2",
      collectionId: "miss",
      title: "Gala Amazonas",
      eyebrow: "Concurso",
      shortDescription: "Fotos reais para observar proporção, movimento e palco.",
      detailDescription: "Fotos reais para observar proporção, movimento e palco.",
      idealFor: ["Concurso de beleza", "Miss", "Top 2", "Desfile"],
      visualDetails: ["Palco amazonense", "Imagem competitiva", "Gala", "Presença fotográfica"],
      gallery: makeGallery("miss/05-p-dsbb02nerhf/slide-01.jpg", "miss/05-p-dsbb02nerhf/slide-02.jpg", "miss/05-p-dsbb02nerhf/slide-04.jpg"),
      backgroundImage: dressImage("miss/05-p-dsbb02nerhf/slide-01.jpg"),
      proof: "3 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido para Miss Amazonas",
    },
    {
      id: "exclusivo-bicho-folharal",
      collectionId: "exclusivos",
      title: "Bicho Folharal",
      eyebrow: "Autoral",
      shortDescription: "Peça autoral com repertório amazonense, textura e força de cena.",
      detailDescription: "Peça autoral com repertório amazonense, textura e força de cena.",
      idealFor: ["Figurino autoral", "Palco", "Editorial", "Produção especial"],
      visualDetails: ["Conceito amazonense", "Folhas e textura", "Azul e vermelho", "Manifesto visual"],
      gallery: makeGallery("01-kaleb-aguiar-p-dkedk-9t3ps/slide-01.jpg", "01-kaleb-aguiar-p-dkedk-9t3ps/slide-02.jpg"),
      backgroundImage: dressImage("01-kaleb-aguiar-p-dkedk-9t3ps/slide-01.jpg"),
      cardImage: dressImage("01-kaleb-aguiar-p-dkedk-9t3ps/slide-02.jpg"),
      proof: "2 fotos reais do conceito",
      accent: "var(--gold)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "look autoral Bicho Folharal",
    },
    {
      id: "exclusivo-detalhe-autoral",
      collectionId: "exclusivos",
      title: "Textura de ateliê",
      eyebrow: "Alta costura",
      shortDescription: "Detalhe de ateliê com acabamento, trabalho manual e presença artística.",
      detailDescription: "Detalhe de ateliê com acabamento, trabalho manual e presença artística.",
      idealFor: ["Editorial", "Alta costura", "Produção especial", "Cena"],
      visualDetails: ["Detalhe de ateliê", "Textura visual", "Acabamento autoral", "Presença artística"],
      gallery: makeGallery("02-kaleb-aguiar-p-dgyxxoxplrt/slide-01.jpg", "02-kaleb-aguiar-p-dgyxxoxplrt/slide-02.jpg"),
      backgroundImage: dressImage("02-kaleb-aguiar-p-dgyxxoxplrt/slide-01.jpg"),
      proof: "2 fotos reais do conceito",
      accent: "var(--gold)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "look exclusivo de alta costura",
    },
    {
      id: "exclusivo-flor-matizada",
      collectionId: "exclusivos",
      title: "Flor matizada",
      eyebrow: "Lançamento",
      shortDescription: "Criação autoral com cor, volume e imagem de palco.",
      detailDescription: "Criação autoral com cor, volume e imagem de palco.",
      idealFor: ["Lançamento", "Palco", "Editorial", "Produção especial"],
      visualDetails: ["Flor de impacto", "Cor matizada", "Cena autoral", "Volume artistico"],
      gallery: makeGallery("03-mylennaaguiar-p-dwz8ogtdykq/slide-01.jpg", "03-mylennaaguiar-p-dwz8ogtdykq/slide-02.jpg"),
      backgroundImage: dressImage("03-mylennaaguiar-p-dwz8ogtdykq/slide-01.jpg"),
      proof: "2 fotos reais do conceito",
      accent: "var(--gold)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "look exclusivo flor matizada",
    },
    {
      id: "debutantes-acervo-completo",
      collectionId: "debutantes",
      title: "Repertório 15 anos",
      eyebrow: "15 anos",
      shortDescription: "Fotos reais para comparar volume, tons, brilho e entrada.",
      detailDescription: "Fotos reais para comparar volume, tons, brilho e entrada.",
      idealFor: ["15 anos", "Entrada principal", "Ensaio", "Festa classica"],
      visualDetails: ["Volume de princesa", "Tons românticos", "Brilho de palco", "Fotos reais do acervo"],
      gallery: makeGallery("debutantes (2).jpg", "debutantes (1).jpg", "debutante-02.jpg", "debugantes04 (1).jpg", "debugantes04 (2).jpg", "debutantes (3).jpg", "debutantes (4).jpg", "debutantes-03 (1).jpg", "debutantes-03 (2).jpg"),
      backgroundImage: dressImage("debutantes (2).jpg"),
      proof: "9 fotos reais desta modalidade",
      accent: "var(--rose)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "album de debutantes do acervo",
    },
    {
      id: "noiva-andre-nogueira-editorial",
      collectionId: "noiva",
      title: "Noiva externa",
      eyebrow: "Cerimônia",
      shortDescription: "Noiva em contexto fotográfico para avaliar proporção e delicadeza.",
      detailDescription: "Noiva em contexto fotográfico para avaliar proporção e delicadeza.",
      idealFor: ["Noiva", "Editorial", "Cerimônia", "Fotos externas"],
      visualDetails: ["Fotografia editorial", "Leitura cerimonial", "Branco elegante", "Cena romântica"],
      gallery: makeGallery("03-noiva-andre-nogueira-fotografia-0-likes-2-fotos-/noiva-trabalho-03-foto-01-DDN3MmDJYjN.jpg", "03-noiva-andre-nogueira-fotografia-0-likes-2-fotos-/noiva-trabalho-03-foto-02-DDN3MmDJYjN.jpg"),
      backgroundImage: dressImage("03-noiva-andre-nogueira-fotografia-0-likes-2-fotos-/noiva-trabalho-03-foto-01-DDN3MmDJYjN.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ivory)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "referência de noiva editorial",
    },
    {
      id: "miss-acervo-raiz",
      collectionId: "miss",
      title: "Repertório Miss",
      eyebrow: "Miss",
      shortDescription: "Opções de Miss para comparar brilho, faixa e leitura de palco.",
      detailDescription: "Opções de Miss para comparar brilho, faixa e leitura de palco.",
      idealFor: ["Miss", "Concurso", "Faixa", "Apresentação"],
      visualDetails: ["Acervo Miss", "Gala fotografável", "Postura de palco", "Leitura de faixa"],
      gallery: makeGallery("Miss (1).jpg", "Miss (2).jpg", "miss02 (1).jpg", "miss02 (2).jpg"),
      backgroundImage: dressImage("Miss (1).jpg"),
      proof: "4 fotos reais desta modalidade",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "album de Miss do acervo",
    },
    {
      id: "miss-dudezzle-gala",
      collectionId: "miss",
      title: "Gala de concurso",
      eyebrow: "Concurso",
      shortDescription: "Gala de concurso para avaliar brilho, faixa e postura.",
      detailDescription: "Gala de concurso para avaliar brilho, faixa e postura.",
      idealFor: ["Miss", "Concurso", "Gala", "Palco"],
      visualDetails: ["Brilho de concurso", "Presença vertical", "Gala de palco", "Sequência fotográfica"],
      gallery: makeGallery("01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-04-DUrq-KpDL4j.jpg", "01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-01-DUrq-KpDL4j.jpg", "01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-02-DUrq-KpDL4j.jpg"),
      backgroundImage: dressImage("01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-04-DUrq-KpDL4j.jpg"),
      proof: "3 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de gala para Miss",
    },
    {
      id: "miss-vitoria-beatriz-544",
      collectionId: "miss",
      title: "Faixa champagne",
      eyebrow: "Concurso",
      shortDescription: "Look de concurso com postura de palco e imagem de gala.",
      detailDescription: "Look de concurso com postura de palco e imagem de gala.",
      idealFor: ["Miss", "Concurso", "Desfile", "Gala"],
      visualDetails: ["Postura competitiva", "Gala fotografável", "Presença de longe", "Referência de faixa"],
      gallery: makeGallery("02-miss-vitoriabeatrizslv-544-likes-4-fotos-DSTipAiDSfj/miss-trabalho-02-foto-01-DSTipAiDSfj.jpg", "02-miss-vitoriabeatrizslv-544-likes-4-fotos-DSTipAiDSfj/miss-trabalho-02-foto-02-DSTipAiDSfj.jpg"),
      backgroundImage: dressImage("02-miss-vitoriabeatrizslv-544-likes-4-fotos-DSTipAiDSfj/miss-trabalho-02-foto-01-DSTipAiDSfj.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss faixa champagne",
    },
    {
      id: "miss-vitoria-beatriz-403",
      collectionId: "miss",
      title: "Palco elegante",
      eyebrow: "Palco",
      shortDescription: "Miss para palco, com leitura elegante e fotografável.",
      detailDescription: "Miss para palco, com leitura elegante e fotografável.",
      idealFor: ["Palco", "Miss", "Concurso", "Fotos oficiais"],
      visualDetails: ["Leitura de palco", "Gala elegante", "Efeito em foto", "Postura de concurso"],
      gallery: makeGallery("03-miss-vitoriabeatrizslv-403-likes-4-fotos-DSYyoSojTWp/miss-trabalho-03-foto-02-DSYyoSojTWp.jpg", "03-miss-vitoriabeatrizslv-403-likes-4-fotos-DSYyoSojTWp/miss-trabalho-03-foto-01-DSYyoSojTWp.jpg"),
      backgroundImage: dressImage("03-miss-vitoriabeatrizslv-403-likes-4-fotos-DSYyoSojTWp/miss-trabalho-03-foto-02-DSYyoSojTWp.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss para palco",
    },
    {
      id: "miss-vitoria-beatriz-394",
      collectionId: "miss",
      title: "Top faixa gala",
      eyebrow: "Faixa",
      shortDescription: "Look de faixa com impacto de concurso e leitura de vencedora.",
      detailDescription: "Look de faixa com impacto de concurso e leitura de vencedora.",
      idealFor: ["Miss", "Faixa", "Top", "Concurso"],
      visualDetails: ["Leitura de vencedora", "Gala de concurso", "Imagem vertical", "Presença sob luz"],
      gallery: makeGallery("04-miss-vitoriabeatrizslv-394-likes-4-fotos-DSbB02NErhf/miss-trabalho-04-foto-01-DSbB02NErhf.jpg", "04-miss-vitoriabeatrizslv-394-likes-4-fotos-DSbB02NErhf/miss-trabalho-04-foto-02-DSbB02NErhf.jpg"),
      backgroundImage: dressImage("04-miss-vitoriabeatrizslv-394-likes-4-fotos-DSbB02NErhf/miss-trabalho-04-foto-01-DSbB02NErhf.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss com faixa",
    },
    {
      id: "miss-mariana-barroso",
      collectionId: "miss",
      title: "Palco perolado",
      eyebrow: "Concurso",
      shortDescription: "Sequência real para avaliar gala, postura e presença em apresentação.",
      detailDescription: "Sequência real para avaliar gala, postura e presença em apresentação.",
      idealFor: ["Miss", "Concurso", "Gala", "Apresentação"],
      visualDetails: ["Sequência real", "Postura de gala", "Cena de concurso", "Referência para atendimento"],
      gallery: makeGallery("05-miss-marianabarrosonn-0-likes-4-fotos-DXpvWL2lsfX/miss-trabalho-05-foto-02-DXpvWL2lsfX.jpg", "05-miss-marianabarrosonn-0-likes-4-fotos-DXpvWL2lsfX/miss-trabalho-05-foto-01-DXpvWL2lsfX.jpg"),
      backgroundImage: dressImage("05-miss-marianabarrosonn-0-likes-4-fotos-DXpvWL2lsfX/miss-trabalho-05-foto-02-DXpvWL2lsfX.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss palco perolado",
    },
  ],
  process: [
    ["01", "Informe sua data", "Diga data, ocasião, horário e tipo de vestido."],
    ["02", "Escolha uma direção", "Separe cor, brilho, volume e caimento que combinam com o evento."],
    ["03", "Visite com referências", "O ateliê orienta modelos próximos ao que você deseja."],
    ["04", "Consulte sua data", "Gostou do modelo? Consulte as condições para sua data."],
  ],
};

clientConfig.dressItems = clientConfig.dressItems.map(applyDressBackgroundProfile);

export function buildReservationUrl(context = "") {
  const message = context
    ? `Olá, Atelier Kaleb Aguiar. Vim pelo site e quero consultar vestidos para minha data. Tenho interesse em: ${context}.`
    : "Olá, Atelier Kaleb Aguiar. Vim pelo site e quero consultar vestidos para minha data.";
  return `${clientConfig.whatsappUrl}?text=${encodeURIComponent(message)}`;
}
