const image = (name) => `/assets/kaleb-aguiar/${name}`;
const linkImage = (name) => image(`linkpage-curated/${name}`);
const dressImage = (path) => `/assets/Kaleb-aguiar-1/${path}`;
const makeGallery = (...paths) => paths.map(dressImage);

const dressBackgroundVariants = {
  "debutante-boneca": "portrait-tight",
  "noiva-bride-reel": "portrait-tight",
  "miss-beleza-brasil": "portrait-tight",
  "madrinha-kaleb-aguiar": "square-scene",
  "debutante-dress": "square-scene",
  "debutante-rosa-classico": "square-scene",
  "exclusivo-detalhe-autoral": "detail-wash",
};

const dressBackgroundPositions = {
  "madrinha-kaleb-aguiar": "50% 48%",
  "debutante-rosa-classico": "50% 48%",
  "miss-dudezzle-gala": "50% 45%",
  "exclusivo-detalhe-autoral": "50% 42%",
};

const dressBackgroundMobilePositions = {
  "madrinha-kaleb-aguiar": "50% 48%",
  "debutante-rosa-classico": "50% 46%",
  "miss-dudezzle-gala": "50% 42%",
  "exclusivo-detalhe-autoral": "50% 40%",
};

const applyDressBackgroundProfile = (item) => ({
  ...item,
  backgroundVariant: dressBackgroundVariants[item.id] || "portrait-full",
  backgroundPosition: dressBackgroundPositions[item.id] || item.imagePosition || "50% 16%",
  backgroundMobilePosition: dressBackgroundMobilePositions[item.id] || item.mobilePosition || item.imagePosition || "50% 14%",
});

export const clientConfig = {
  brand: "Atelier Kaleb Aguiar",
  descriptor: "Designer de moda",
  handle: "@kaleb_aguiar",
  instagramUrl: "https://www.instagram.com/kaleb_aguiar/",
  facebookUrl: "https://www.facebook.com/p/Kaleb-Aguiar-100063493009146/",
  whatsappUrl: "https://wa.me/5592993509850",
  fallbackContactUrl: "https://wa.me/5592993509850",
  phoneDisplay: "+55 92 99350-9850",
  contactMode: "whatsapp",
  contactNote: "Atendimento inicial pelo WhatsApp. Voce pode tirar duvidas e visitar o atelie sem compromisso antes de decidir.",
  city: "Manaus, AM",
  address: "Rua Rio Purus 1078 - Vieiralves, Manaus - AM",
  addressShort: "Rua Rio Purus 1078 - Vieiralves",
  promise: "Reserve o vestido da sua grande entrada.",
  positioning: "Vestidos para debutantes, madrinhas, formandas, noivas, Miss e produções exclusivas em Manaus. Veja referências, escolha uma direção e visite o ateliê com mais clareza antes de decidir.",
  proof: ["Debutantes", "Madrinhas", "Moda festa", "Formatura", "Noivas", "Miss", "Exclusivos"],
  assets: {
    logo: image("kaleb-logo.jpeg"),
    hero: image("bg-hero-section-1-optimized.webp"),
    heroSlides: [
      {
        src: image("bg-hero-section-1-optimized.webp"),
        position: "center top",
        mobilePosition: "75% 24%",
        scaleStart: "1",
        scaleEnd: "1.004",
        shiftXEnd: "-0.04%",
        shiftYEnd: "-0.03%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.002",
        mobileShiftYStart: "14px",
        mobileShiftYEnd: "12px",
        frameWidth: "90%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "76%",
        shortFrameBottom: "0px",
      },
      {
        src: image("bg-hero-section3-optimized.webp"),
        position: "center top",
        mobilePosition: "77% 24%",
        scaleStart: "1",
        scaleEnd: "1.004",
        shiftXEnd: "-0.04%",
        shiftYEnd: "-0.03%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.002",
        mobileShiftYStart: "14px",
        mobileShiftYEnd: "12px",
        frameWidth: "88.5%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "74%",
        shortFrameBottom: "0px",
      },
      {
        src: image("bg-hero-section2-optimized.webp"),
        position: "center top",
        mobilePosition: "76% 26%",
        scaleStart: "1",
        scaleEnd: "1.004",
        shiftXEnd: "-0.04%",
        shiftYEnd: "-0.03%",
        mobileScaleStart: "1",
        mobileScaleEnd: "1.002",
        mobileShiftYStart: "14px",
        mobileShiftYEnd: "12px",
        frameWidth: "88.5%",
        frameHeight: "100%",
        frameRight: "0px",
        frameBottom: "0px",
        shortFrameWidth: "74%",
        shortFrameBottom: "0px",
      },
    ],
    heroMobileBoi: image("mobile-bg-boi-final.png"),
    heroMobileNicole: image("mobile-bg-nicole-red-final.png"),
    green: image("vestido-verde-plumas-corredor.png"),
    red: image("vestido-vermelho-fenda.png"),
    blue: image("figurino-azul-palco.png"),
    sash: image("vestido-verde-faixa.png"),
    lilac: image("vestido-lilas-baloes.png"),
    reserveHorizontal: dressImage("debutantes-03 (1).jpg"),
    silver: image("vestido-prata-noite.png"),
  },
  links: {
    maps: "https://www.google.com/maps/search/?api=1&query=Rua%20Rio%20Purus%201078%2C%20Vieiralves%2C%20Manaus%20-%20AM",
    uber: "https://m.uber.com/ul/?action=setPickup&pickup=my_location&dropoff[nickname]=Atelier%20Kaleb%20Aguiar&dropoff[formatted_address]=Rua%20Rio%20Purus%201078%2C%20Vieiralves%2C%20Manaus%20-%20AM",
  },
  categories: [
    {
      id: "debutante",
      label: "Debutantes",
      eyebrow: "15 anos",
      title: "Ver vestidos de debutantes",
      body: "Vestidos com volume, brilho e presenca para uma entrada marcante.",
      image: image("hero-debutante-roxo-escadaria.png"),
      accent: "var(--rose)",
    },
    {
      id: "madrinha",
      label: "Madrinha e Moda Festa",
      eyebrow: "Eventos e casamentos",
      title: "Ver madrinha e moda festa",
      body: "Modelos elegantes para casamento, recepcao, fotos e eventos especiais.",
      image: linkImage("cover-madrinha-rosa-festa.webp"),
      accent: "var(--jade)",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Colacao e baile",
      title: "Ver vestidos de formatura",
      body: "Bordados, fendas e silhuetas de impacto para celebrar sua conquista.",
      image: image("vestido-vermelho-fenda.png"),
      accent: "var(--ruby)",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimonia",
      title: "Consultar vestidos de noiva",
      body: "Opcoes para quem procura uma peca delicada, marcante e fotografavel.",
      image: image("vestido-prata-noite.png"),
      accent: "var(--ivory)",
    },
    {
      id: "palco",
      label: "Exclusivos",
      eyebrow: "Modelos especiais",
      title: "Ver modelos exclusivos",
      body: "Pecas de impacto para ensaios, eventos, palco e producoes especiais.",
      image: image("figurino-azul-palco.png"),
      accent: "var(--sapphire)",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      title: "Ver vestidos para Miss",
      body: "Pecas de destaque para concurso, apresentacao, palco e momentos de presenca.",
      image: image("vestido-lilas-baloes.png"),
      accent: "var(--violet)",
    },
  ],
  linkpageCategories: [
    {
      id: "debutante",
      label: "Debutantes",
      eyebrow: "15 anos",
      title: "Ver vestidos de debutantes",
      body: "Vestidos com volume, brilho e presenca para uma entrada marcante.",
      image: linkImage("cover-debutante-rosa-palco.webp"),
      accent: "var(--rose)",
      imagePosition: "50% 18%",
      mobilePosition: "52% 12%",
      tilePosition: "50% 16%",
    },
    {
      id: "madrinha",
      label: "Madrinha e Moda Festa",
      eyebrow: "Eventos e casamentos",
      title: "Ver madrinha e moda festa",
      body: "Modelos elegantes para casamento, recepcao, fotos e eventos especiais.",
      image: linkImage("cover-madrinha-rosa-festa.webp"),
      accent: "var(--jade)",
      imagePosition: "50% 10%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 14%",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Colacao e baile",
      title: "Ver vestidos de formatura",
      body: "Bordados, fendas e silhuetas de impacto para celebrar sua conquista.",
      image: linkImage("cover-formatura-verde-evento.webp"),
      accent: "var(--ruby)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 12%",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimonia",
      title: "Consultar vestidos de noiva",
      body: "Opcoes para quem procura uma peca delicada, marcante e fotografavel.",
      image: linkImage("cover-noiva-branco-noite.webp"),
      accent: "var(--ivory)",
      imagePosition: "58% 18%",
      mobilePosition: "58% 12%",
      tilePosition: "58% 16%",
    },
    {
      id: "palco",
      label: "Exclusivos",
      eyebrow: "Modelos especiais",
      title: "Ver modelos exclusivos",
      body: "Pecas de impacto para ensaios, eventos, palco e producoes especiais.",
      image: linkImage("cover-exclusivo-vermelho-flor.webp"),
      accent: "var(--sapphire)",
      imagePosition: "50% 8%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 12%",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      title: "Ver vestidos para Miss",
      body: "Pecas de destaque para concurso, apresentacao, palco e momentos de presenca.",
      image: linkImage("cover-miss-prata-coroa.webp"),
      accent: "var(--violet)",
      imagePosition: "50% 8%",
      mobilePosition: "50% 8%",
      tilePosition: "50% 10%",
    },
  ],
  dressCollections: [
    {
      id: "madrinha-moda-festa",
      label: "Madrinha e Moda Festa",
      eyebrow: "Casamentos e eventos",
      headline: "Festa com presenca de atelie.",
      body: "Madrinhas e moda festa em fotos reais, com caimento, cor e impacto organizados para consulta rapida.",
      accent: "var(--jade)",
    },
    {
      id: "debutantes",
      label: "Debutantes",
      eyebrow: "15 anos",
      headline: "Entrada de 15 anos em cena.",
      body: "Volume, brilho e romantismo para a debutante escolher referencias antes da prova no atelie.",
      accent: "var(--rose)",
      albumCover: dressImage("debutantes (2).jpg"),
      featuredItemId: "debutantes-acervo-completo",
    },
    {
      id: "formatura",
      label: "Formatura",
      eyebrow: "Baile e colacao",
      headline: "Gala para a noite da conquista.",
      body: "Vestidos de baile e colacao com leitura fotografica, presenca e acabamento de festa.",
      accent: "var(--ruby)",
    },
    {
      id: "noiva",
      label: "Noiva",
      eyebrow: "Cerimonia",
      headline: "Noiva com cena e delicadeza.",
      body: "Referencias brancas e cerimoniais para visualizar proporcao, imagem e romantismo antes do atendimento.",
      accent: "var(--ivory)",
      albumCover: dressImage("noiva/05-p-dqnvidwefud/slide-01.jpg"),
      featuredItemId: "noiva-laila",
    },
    {
      id: "miss",
      label: "Miss",
      eyebrow: "Faixa e palco",
      headline: "Palco, faixa e autoridade.",
      body: "Vestidos de concurso com postura, gala e leitura forte sob luz de apresentacao.",
      accent: "var(--violet)",
    },
    {
      id: "exclusivos",
      label: "Exclusivos",
      eyebrow: "Autoral e cena",
      headline: "Alta-costura autoral para festas, palco e grandes entradas.",
      body: "Criacoes especiais que mostram repertorio, textura e assinatura de atelie sem parecer vestido comum.",
      accent: "var(--gold)",
      albumCover: dressImage("03-mylennaaguiar-p-dwz8ogtdykq/slide-01.jpg"),
      featuredItemId: "exclusivo-flor-matizada",
    },
  ],
  dressItems: [
    {
      id: "madrinha-yari-angel",
      collectionId: "madrinha-moda-festa",
      title: "Rose de gala",
      eyebrow: "Madrinha",
      shortDescription: "Um look suave, fotografavel e elegante para casamento, recepcao e noite especial.",
      detailDescription: "A leitura rose cria um efeito delicado sem perder presenca. E uma escolha para quem quer aparecer com classe, sustentando o vestido nas fotos e no movimento da festa.",
      idealFor: ["Casamento", "Madrinha", "Recepcao", "Fotos oficiais"],
      visualDetails: ["Tom rose elegante", "Caimento de gala", "Presenca suave", "Boa leitura em foto"],
      gallery: makeGallery("04-madrinha-moda-festa-yari-angel-467-likes-2-fotos/debutantes (1).jpg", "04-madrinha-moda-festa-yari-angel-467-likes-2-fotos/debutantes (2).jpg"),
      backgroundImage: dressImage("04-madrinha-moda-festa-yari-angel-467-likes-2-fotos/debutantes (1).jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--jade)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 14%",
      whatsappContext: "madrinha e moda festa, look rose",
    },
    {
      id: "madrinha-kaleb-aguiar",
      collectionId: "madrinha-moda-festa",
      title: "Blush cerimonial",
      eyebrow: "Moda festa",
      shortDescription: "Look compacto e refinado para quem quer um vestido bonito, direto e de efeito nobre.",
      detailDescription: "A proposta funciona como referencia para eventos formais em que a cliente quer elegancia sem excesso. O popup organiza o pedido para o atelie entender cor, ocasiao e disponibilidade.",
      idealFor: ["Casamento civil", "Recepcao", "Convidada premium", "Evento noturno"],
      visualDetails: ["Tom blush", "Elegancia limpa", "Silhueta fotografavel", "Acabamento de festa"],
      gallery: makeGallery("05-madrinha-moda-festa-kaleb-aguiar-289-likes-2/madrinha-moda-festa-trabalho-05-foto-01-DB9P7e-PSbg.jpg", "05-madrinha-moda-festa-kaleb-aguiar-289-likes-2/madrinha-moda-festa-trabalho-05-foto-02-DB9P7e-PSbg.jpg"),
      backgroundImage: dressImage("05-madrinha-moda-festa-kaleb-aguiar-289-likes-2/madrinha-moda-festa-trabalho-05-foto-01-DB9P7e-PSbg.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--jade)",
      imagePosition: "50% 50%",
      mobilePosition: "50% 50%",
      whatsappContext: "madrinha e moda festa, look blush",
    },
    {
      id: "madrinha-verde-plumas",
      collectionId: "madrinha-moda-festa",
      title: "Verde festa",
      eyebrow: "Moda festa",
      shortDescription: "Referencia verde de impacto para casamento, evento noturno e producao com movimento.",
      detailDescription: "A imagem entra como apoio visual da vitrine atual para completar o trilho de moda festa com leitura de corpo mais clara. A consulta deve confirmar disponibilidade, prova e modelos proximos no atelie.",
      idealFor: ["Madrinha", "Evento noturno", "Recepcao", "Fotos de entrada"],
      visualDetails: ["Verde de presenca", "Brilho de festa", "Movimento elegante", "Leitura de corpo"],
      gallery: [linkImage("cover-formatura-verde-evento.webp")],
      backgroundImage: linkImage("cover-formatura-verde-evento.webp"),
      proof: "Imagem de apoio do acervo",
      accent: "var(--jade)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 14%",
      whatsappContext: "madrinha e moda festa, vestido verde",
    },
    {
      id: "debutante-boneca",
      collectionId: "debutantes",
      title: "Princesa azul",
      eyebrow: "15 anos",
      shortDescription: "Vestido com leitura de sonho, volume e delicadeza para entrada de debutante.",
      detailDescription: "A composicao trabalha o imaginario de boneca e festa de 15 anos. E ideal para quem quer uma entrada marcante, com vestido protagonista e visual de memoria.",
      idealFor: ["15 anos", "Entrada principal", "Ensaio fotografico", "Festa classica"],
      visualDetails: ["Volume de debutante", "Leitura romantica", "Presenca de palco", "Foto de impacto"],
      gallery: makeGallery("debutantes-01/slide-01.jpg", "debutantes-01/slide-02.jpg"),
      backgroundImage: dressImage("debutantes-01/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--rose)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "debutante boneca",
    },
    {
      id: "debutante-dress",
      collectionId: "debutantes",
      title: "Sonho de 15 anos",
      eyebrow: "15 anos",
      shortDescription: "Uma opcao de debutante com presenca doce e leitura editorial para fotos.",
      detailDescription: "O look foi classificado como vestido de 15 anos e serve para guiar a conversa sobre volume, cor e efeito de entrada antes da visita ao atelie.",
      idealFor: ["15 anos", "Fotos antes da festa", "Entrada", "Recepcao"],
      visualDetails: ["Estetica delicada", "Efeito princesa", "Linha romantica", "Boa leitura vertical"],
      gallery: makeGallery("debutantes-01 (3)/slide-01.jpg"),
      backgroundImage: dressImage("debutantes-01 (3)/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--rose)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de debutante dress",
    },
    {
      id: "debutante-rosa-classico",
      collectionId: "debutantes",
      title: "Rosa classico",
      eyebrow: "15 anos",
      shortDescription: "Rosa de festa com volume e acabamento pensado para uma entrada marcante.",
      detailDescription: "A galeria mostra duas leituras do mesmo momento, ajudando a cliente a avaliar cor, postura e impacto visual antes de pedir disponibilidade.",
      idealFor: ["15 anos", "Festa classica", "Baile", "Fotos de familia"],
      visualDetails: ["Rosa debutante", "Volume presente", "Acabamento cenico", "Movimento de festa"],
      gallery: makeGallery("debutantes-01 (4)/slide-01.jpg", "debutantes-01 (4)/slide-02.jpg"),
      backgroundImage: dressImage("debutantes-01 (4)/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--rose)",
      imagePosition: "50% 45%",
      mobilePosition: "50% 42%",
      whatsappContext: "vestido de debutante rosa classico",
    },
    {
      id: "debutante-ensaio",
      collectionId: "debutantes",
      title: "Editorial 15 anos",
      eyebrow: "Ensaio",
      shortDescription: "Referencias de 15 anos com cor, brilho, volume e cena para orientar a escolha.",
      detailDescription: "A proposta valoriza a fotografia da debutante e ajuda a familia a visualizar o vestido como parte da narrativa do aniversario, reunindo referencias que estavam no acervo mas ainda nao apareciam no album principal.",
      idealFor: ["Ensaio fotografico", "15 anos", "Entrada", "Editorial familiar"],
      visualDetails: ["Imagem de debutante", "Volume fotografavel", "Brilho de festa", "Cena de memoria"],
      gallery: [
        image("vestido-lilas-baloes.png"),
        image("hero-debutante-roxo-escadaria.png"),
        linkImage("cover-debutante-rosa-palco.webp"),
        dressImage("debutantes-01 (2)/slide-01.jpg"),
      ],
      backgroundImage: image("vestido-lilas-baloes.png"),
      proof: "4 fotos reais de 15 anos",
      accent: "var(--rose)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "referencias de debutante para ensaio de 15 anos",
    },
    {
      id: "formatura-medicina",
      collectionId: "formatura",
      title: "Gala da conquista",
      eyebrow: "Baile",
      shortDescription: "Vestido para formanda que quer celebrar a conquista com gala e presenca.",
      detailDescription: "A proposta trabalha o momento da conquista com gala e presenca. A apresentacao conduz para uma conversa sobre data, cor e disponibilidade.",
      idealFor: ["Baile de formatura", "Medicina", "Colacao", "Fotos oficiais"],
      visualDetails: ["Gala de formatura", "Impacto em foto", "Linha celebrativa", "Acabamento nobre"],
      gallery: makeGallery("formatura02/slide-01.jpg", "formatura02/slide-02.jpg"),
      backgroundImage: dressImage("formatura02/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ruby)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de formatura gala da conquista",
    },
    {
      id: "formatura-vermelho-gala",
      collectionId: "formatura",
      title: "Vermelho de gala",
      eyebrow: "Gala",
      shortDescription: "Vermelho de impacto para formanda que quer presenca forte na noite.",
      detailDescription: "O vermelho cria autoridade visual e funciona para quem deseja uma imagem poderosa no baile. A consulta deve validar disponibilidade e prova no atelie.",
      idealFor: ["Baile", "Formanda", "Evento noturno", "Fotos de conquista"],
      visualDetails: ["Vermelho intenso", "Presenca de gala", "Silhueta marcante", "Efeito noturno"],
      gallery: makeGallery("formatura03/slide-01.jpg", "formatura03/slide-02.jpg"),
      backgroundImage: dressImage("formatura03/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ruby)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido vermelho de formatura",
    },
    {
      id: "formatura-alta-costura",
      collectionId: "formatura",
      title: "Gala de atelier",
      eyebrow: "Exclusivo",
      shortDescription: "Modelo de gala com leitura de alta costura para uma noite especial.",
      detailDescription: "A peca funciona como referencia para quem procura algo menos comum, com acabamento de atelie e presenca visual nas fotos.",
      idealFor: ["Formatura", "Gala", "Cliente especial", "Evento formal"],
      visualDetails: ["Modelo exclusivo", "Leitura sofisticada", "Acabamento de atelie", "Presenca editorial"],
      gallery: makeGallery("fomatura/slide-01.jpg"),
      backgroundImage: dressImage("fomatura/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ruby)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 12%",
      whatsappContext: "formatura alta costura",
    },
    {
      id: "noiva-vestido-classico",
      collectionId: "noiva",
      title: "Noiva classica",
      eyebrow: "Noiva",
      shortDescription: "Vestido de noiva com leitura delicada para cerimonia e fotografia.",
      detailDescription: "Uma referencia clara para abrir conversa sobre noiva, prova e estilo. O foco e orientar a visita sem prometer disponibilidade automatica.",
      idealFor: ["Cerimonia", "Noiva", "Fotos do casal", "Casamento classico"],
      visualDetails: ["Branco delicado", "Leitura de cerimonia", "Foto limpa", "Presenca romantica"],
      gallery: makeGallery("noiva/01-p-c0tw3-qosfj/slide-01.jpg"),
      backgroundImage: dressImage("noiva/01-p-c0tw3-qosfj/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ivory)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de noiva classico",
    },
    {
      id: "noiva-janaina",
      collectionId: "noiva",
      title: "Noiva jardim",
      eyebrow: "Noiva",
      shortDescription: "Vestido com delicadeza de noiva e leitura elegante para a cerimonia.",
      detailDescription: "A galeria ajuda a observar a mesma proposta em mais de um enquadramento, deixando a consulta mais objetiva no WhatsApp.",
      idealFor: ["Cerimonia", "Noiva", "Casamento diurno", "Fotos externas"],
      visualDetails: ["Branco suave", "Caimento delicado", "Elegancia classica", "Imagem limpa"],
      gallery: makeGallery("noiva/02-p-colo74doqs9/slide-01.jpg", "noiva/02-p-colo74doqs9/slide-02.jpg"),
      backgroundImage: dressImage("noiva/02-p-colo74doqs9/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ivory)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 14%",
      whatsappContext: "vestido de noiva jardim",
    },
    {
      id: "noiva-bride-reel",
      collectionId: "noiva",
      title: "Noiva editorial",
      eyebrow: "Noiva",
      shortDescription: "Referencia vertical para noiva com foco em presenca e composicao de beleza.",
      detailDescription: "Uma opcao para orientar quem chega pelo celular e quer mostrar rapidamente um estilo de noiva para o atendimento.",
      idealFor: ["Noiva", "Making of", "Editorial bride", "Referencia de prova"],
      visualDetails: ["Imagem vertical", "Foco na noiva", "Clima delicado", "Leitura de beleza"],
      gallery: makeGallery("noiva/03-reel-c1m55dnlpvf/slide-01.jpg"),
      backgroundImage: dressImage("noiva/03-reel-c1m55dnlpvf/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ivory)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "referencia de noiva bride",
    },
    {
      id: "noiva-nayara-gabriel",
      collectionId: "noiva",
      title: "Noiva romantica",
      eyebrow: "Casamento",
      shortDescription: "Vestido de casamento com leitura romantica e presenca completa de cerimonia.",
      detailDescription: "As duas fotos ajudam a avaliar volume, proporcao e efeito fotografico do vestido em contexto de casamento.",
      idealFor: ["Casamento", "Cerimonia", "Fotos oficiais", "Entrada da noiva"],
      visualDetails: ["Branco cerimonial", "Volume romantico", "Imagem de casamento", "Acabamento delicado"],
      gallery: makeGallery("noiva/04-p-djsm0qip8yd1jef5-7rvto7shvaf5xs0khevq80/slide-01.jpg", "noiva/04-p-djsm0qip8yd1jef5-7rvto7shvaf5xs0khevq80/slide-02.jpg"),
      backgroundImage: dressImage("noiva/04-p-djsm0qip8yd1jef5-7rvto7shvaf5xs0khevq80/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ivory)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de noiva romantica",
    },
    {
      id: "noiva-laila",
      collectionId: "noiva",
      title: "Noiva delicada",
      eyebrow: "Noiva",
      shortDescription: "Noiva com imagem vertical forte para consultar estilo, prova e disponibilidade.",
      detailDescription: "A foto serve como referencia direta para quem quer uma noiva com presenca visual sem perder suavidade.",
      idealFor: ["Noiva", "Cerimonia", "Ensaio", "Referencia de estilo"],
      visualDetails: ["Imagem vertical", "Leitura romantica", "Presenca suave", "Detalhe de noiva"],
      gallery: makeGallery("noiva/05-p-dqnvidwefud/slide-01.jpg"),
      backgroundImage: dressImage("noiva/05-p-dqnvidwefud/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--ivory)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de noiva delicada",
    },
    {
      id: "miss-dress-faixa",
      collectionId: "miss",
      title: "Gala de faixa",
      eyebrow: "Miss",
      shortDescription: "Vestido para concurso com postura, faixa e leitura de palco.",
      detailDescription: "A proposta foi classificada como dress para Miss. O foco do popup e facilitar a consulta por faixa, gala e presenca em palco.",
      idealFor: ["Concurso", "Miss", "Desfile", "Apresentacao"],
      visualDetails: ["Postura de palco", "Leitura de faixa", "Gala", "Imagem de autoridade"],
      gallery: makeGallery("miss/01-p-czfnxksufxn/slide-01.jpg", "miss/01-p-czfnxksufxn/slide-02.jpg"),
      backgroundImage: dressImage("miss/01-p-czfnxksufxn/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido para Miss com faixa",
    },
    {
      id: "miss-beleza-brasil",
      collectionId: "miss",
      title: "Gala nacional",
      eyebrow: "Concurso",
      shortDescription: "Look de concurso com leitura vertical e impacto de passarela.",
      detailDescription: "A imagem trabalha o universo de concurso nacional e ajuda a cliente a pedir um vestido com presenca para palco.",
      idealFor: ["Miss", "Concurso", "Passarela", "Gala"],
      visualDetails: ["Imagem de passarela", "Presenca vertical", "Gala de concurso", "Impacto sob luz"],
      gallery: makeGallery("miss/02-reel-dkacr8wnj1b/slide-01.jpg"),
      backgroundImage: dressImage("miss/02-reel-dkacr8wnj1b/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--violet)",
      imagePosition: "50% 10%",
      mobilePosition: "50% 8%",
      whatsappContext: "vestido de gala nacional para Miss",
    },
    {
      id: "miss-rainha-cupuacu",
      collectionId: "miss",
      title: "Gala rainha regional",
      eyebrow: "Gala",
      shortDescription: "Vestido de gala para rainha, concurso e momento de grande presenca.",
      detailDescription: "A legenda menciona rainha do cupuacu e vestido de gala. A peca reforca o Kaleb como atelie de palco e cultura visual amazonense.",
      idealFor: ["Rainha", "Concurso", "Gala", "Evento cultural"],
      visualDetails: ["Gala amazonense", "Leitura de rainha", "Presenca cultural", "Acabamento cenico"],
      gallery: makeGallery("miss/03-p-dowft85jolk/slide-01.jpg", "miss/03-p-dowft85jolk/slide-02.jpg"),
      backgroundImage: dressImage("miss/03-p-dowft85jolk/slide-01.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de gala Rainha do Cupuacu",
    },
    {
      id: "miss-continente-gala",
      collectionId: "miss",
      title: "Gala continental",
      eyebrow: "Gala",
      shortDescription: "Vestido de gala para desfile, concurso e postura de palco.",
      detailDescription: "A referencia aponta Miss Continente Brasil e desfile de gala. E um look para consulta objetiva quando a cliente precisa de impacto e elegancia.",
      idealFor: ["Desfile de gala", "Miss", "Concurso", "Palco"],
      visualDetails: ["Gala formal", "Postura de desfile", "Presenca de longe", "Brilho controlado"],
      gallery: makeGallery("miss/04-p-drle-cnday5/slide-01.jpg"),
      backgroundImage: dressImage("miss/04-p-drle-cnday5/slide-01.jpg"),
      proof: "Foto real do look",
      accent: "var(--violet)",
      imagePosition: "50% 12%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido Miss Continente gala",
    },
    {
      id: "miss-amazonas-top2",
      collectionId: "miss",
      title: "Gala Amazonas",
      eyebrow: "Concurso",
      shortDescription: "Vestido de concurso com leitura de palco e resultado de alta presenca.",
      detailDescription: "O conjunto reforca concurso de belezas e contexto amazonense. As fotos devem abrir em galeria para mostrar proporcao e movimento.",
      idealFor: ["Concurso de beleza", "Miss", "Top 2", "Desfile"],
      visualDetails: ["Palco amazonense", "Imagem competitiva", "Gala", "Presenca fotografica"],
      gallery: makeGallery("miss/05-p-dsbb02nerhf/slide-01.jpg", "miss/05-p-dsbb02nerhf/slide-02.jpg", "miss/05-p-dsbb02nerhf/slide-04.jpg"),
      backgroundImage: dressImage("miss/05-p-dsbb02nerhf/slide-01.jpg"),
      proof: "3 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido para Miss Amazonas",
    },
    {
      id: "exclusivo-bicho-folharal",
      collectionId: "exclusivos",
      title: "Bicho Folharal",
      eyebrow: "Autoral",
      shortDescription: "Look manifesto com referencia amazonense, cena e alta costura autoral.",
      detailDescription: "Uma peca de impacto que mostra o atelie como criador de conceito. Deve aparecer como prova de assinatura visual, nao como vestido comum de aluguel.",
      idealFor: ["Figurino autoral", "Palco", "Editorial", "Producao especial"],
      visualDetails: ["Conceito amazonense", "Folhas e textura", "Azul e vermelho", "Manifesto visual"],
      gallery: makeGallery("01-kaleb-aguiar-p-dkedk-9t3ps/slide-01.jpg", "01-kaleb-aguiar-p-dkedk-9t3ps/slide-02.jpg"),
      backgroundImage: dressImage("01-kaleb-aguiar-p-dkedk-9t3ps/slide-01.jpg"),
      cardImage: dressImage("01-kaleb-aguiar-p-dkedk-9t3ps/slide-02.jpg"),
      proof: "2 fotos reais do conceito",
      accent: "var(--gold)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "look autoral Bicho Folharal",
    },
    {
      id: "exclusivo-detalhe-autoral",
      collectionId: "exclusivos",
      title: "Textura de atelier",
      eyebrow: "Alta costura",
      shortDescription: "Look de detalhe e textura para mostrar acabamento, cena e trabalho manual.",
      detailDescription: "A galeria entra como prova de acabamento e linguagem autoral. E ideal para elevar a percepcao do site alem de catalogo.",
      idealFor: ["Editorial", "Alta costura", "Producao especial", "Cena"],
      visualDetails: ["Detalhe de atelie", "Textura visual", "Acabamento autoral", "Presenca artistica"],
      gallery: makeGallery("02-kaleb-aguiar-p-dgyxxoxplrt/slide-01.jpg", "02-kaleb-aguiar-p-dgyxxoxplrt/slide-02.jpg"),
      backgroundImage: dressImage("02-kaleb-aguiar-p-dgyxxoxplrt/slide-01.jpg"),
      proof: "2 fotos reais do conceito",
      accent: "var(--gold)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "look exclusivo de alta costura",
    },
    {
      id: "exclusivo-flor-matizada",
      collectionId: "exclusivos",
      title: "Flor matizada",
      eyebrow: "Lancamento",
      shortDescription: "Indumentaria de impacto com flor, cor e imagem de palco.",
      detailDescription: "A proposta tem energia de lancamento e fantasia. No site, funciona como prova de repertorio visual e capacidade cenica do atelie.",
      idealFor: ["Lancamento", "Palco", "Editorial", "Producao especial"],
      visualDetails: ["Flor de impacto", "Cor matizada", "Cena autoral", "Volume artistico"],
      gallery: makeGallery("03-mylennaaguiar-p-dwz8ogtdykq/slide-01.jpg", "03-mylennaaguiar-p-dwz8ogtdykq/slide-02.jpg"),
      backgroundImage: dressImage("03-mylennaaguiar-p-dwz8ogtdykq/slide-01.jpg"),
      proof: "2 fotos reais do conceito",
      accent: "var(--gold)",
      imagePosition: "50% 18%",
      mobilePosition: "50% 12%",
      whatsappContext: "look exclusivo flor matizada",
    },
    {
      id: "debutantes-acervo-completo",
      collectionId: "debutantes",
      title: "Album 15 anos",
      eyebrow: "15 anos",
      shortDescription: "Conjunto de referencias de debutante para comparar volume, cor, brilho e presenca.",
      detailDescription: "Este album junta as imagens soltas do acervo de debutantes. Ele serve para a cliente olhar estilos proximos, escolher uma direcao visual e mandar a referencia certa para o atelie antes da visita.",
      idealFor: ["15 anos", "Entrada principal", "Ensaio", "Festa classica"],
      visualDetails: ["Volume de princesa", "Tons romanticos", "Brilho de palco", "Fotos reais do acervo"],
      gallery: makeGallery("debutantes (2).jpg", "debutantes (1).jpg", "debutante-02.jpg", "debugantes04 (1).jpg", "debugantes04 (2).jpg", "debutantes (3).jpg", "debutantes (4).jpg", "debutantes-03 (1).jpg", "debutantes-03 (2).jpg"),
      backgroundImage: dressImage("debutantes (2).jpg"),
      proof: "9 fotos reais desta modalidade",
      accent: "var(--rose)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "album de debutantes do acervo",
    },
    {
      id: "noiva-andre-nogueira-editorial",
      collectionId: "noiva",
      title: "Noiva externa",
      eyebrow: "Cerimonia",
      shortDescription: "Noiva com fotografia editorial para visualizar vestido, postura e cena.",
      detailDescription: "A galeria entra como referencia de noiva em contexto fotografico. A cliente consegue observar proporcao, delicadeza e efeito de cerimonia antes de pedir disponibilidade.",
      idealFor: ["Noiva", "Editorial", "Cerimonia", "Fotos externas"],
      visualDetails: ["Fotografia editorial", "Leitura cerimonial", "Branco elegante", "Cena romantica"],
      gallery: makeGallery("03-noiva-andre-nogueira-fotografia-0-likes-2-fotos-/noiva-trabalho-03-foto-01-DDN3MmDJYjN.jpg", "03-noiva-andre-nogueira-fotografia-0-likes-2-fotos-/noiva-trabalho-03-foto-02-DDN3MmDJYjN.jpg"),
      backgroundImage: dressImage("03-noiva-andre-nogueira-fotografia-0-likes-2-fotos-/noiva-trabalho-03-foto-01-DDN3MmDJYjN.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--ivory)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "referencia de noiva editorial",
    },
    {
      id: "miss-acervo-raiz",
      collectionId: "miss",
      title: "Album Miss",
      eyebrow: "Miss",
      shortDescription: "Referencias soltas de Miss para comparar brilho, faixa e leitura de palco.",
      detailDescription: "Este album organiza as imagens avulsas de Miss dentro do acervo. Ele amplia a escolha da cliente e evita que fotos importantes fiquem fora da vitrine.",
      idealFor: ["Miss", "Concurso", "Faixa", "Apresentacao"],
      visualDetails: ["Acervo Miss", "Gala fotografavel", "Postura de palco", "Leitura de faixa"],
      gallery: makeGallery("Miss (1).jpg", "Miss (2).jpg", "miss02 (1).jpg", "miss02 (2).jpg"),
      backgroundImage: dressImage("Miss (1).jpg"),
      proof: "4 fotos reais desta modalidade",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "album de Miss do acervo",
    },
    {
      id: "miss-dudezzle-gala",
      collectionId: "miss",
      title: "Gala de concurso",
      eyebrow: "Concurso",
      shortDescription: "Gala de concurso com registros complementares para avaliar brilho e postura.",
      detailDescription: "A sequencia ajuda a enxergar o vestido em mais de um enquadramento, mantendo foco em palco, faixa e presenca de competicao.",
      idealFor: ["Miss", "Concurso", "Gala", "Palco"],
      visualDetails: ["Brilho de concurso", "Presenca vertical", "Gala de palco", "Sequencia fotografica"],
      gallery: makeGallery("01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-04-DUrq-KpDL4j.jpg", "01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-01-DUrq-KpDL4j.jpg", "01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-02-DUrq-KpDL4j.jpg"),
      backgroundImage: dressImage("01-miss-dudezzle-207-likes-5-fotos/miss-trabalho-01-foto-04-DUrq-KpDL4j.jpg"),
      proof: "3 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 16%",
      mobilePosition: "50% 12%",
      whatsappContext: "vestido de gala para Miss",
    },
    {
      id: "miss-vitoria-beatriz-544",
      collectionId: "miss",
      title: "Faixa champagne",
      eyebrow: "Concurso",
      shortDescription: "Look de concurso com postura de palco e imagem de gala.",
      detailDescription: "Referencia para quem precisa sustentar presenca em apresentacao e quer mandar ao atelie um direcionamento claro de Miss.",
      idealFor: ["Miss", "Concurso", "Desfile", "Gala"],
      visualDetails: ["Postura competitiva", "Gala fotografavel", "Presenca de longe", "Referencia de faixa"],
      gallery: makeGallery("02-miss-vitoriabeatrizslv-544-likes-4-fotos-DSTipAiDSfj/miss-trabalho-02-foto-01-DSTipAiDSfj.jpg", "02-miss-vitoriabeatrizslv-544-likes-4-fotos-DSTipAiDSfj/miss-trabalho-02-foto-02-DSTipAiDSfj.jpg"),
      backgroundImage: dressImage("02-miss-vitoriabeatrizslv-544-likes-4-fotos-DSTipAiDSfj/miss-trabalho-02-foto-01-DSTipAiDSfj.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss faixa champagne",
    },
    {
      id: "miss-vitoria-beatriz-403",
      collectionId: "miss",
      title: "Palco elegante",
      eyebrow: "Palco",
      shortDescription: "Referencia de Miss para palco, com leitura elegante e fotografavel.",
      detailDescription: "O album complementa as opcoes de concurso e ajuda a cliente a comparar efeito de palco antes de conversar com o atelie.",
      idealFor: ["Palco", "Miss", "Concurso", "Fotos oficiais"],
      visualDetails: ["Leitura de palco", "Gala elegante", "Efeito em foto", "Postura de concurso"],
      gallery: makeGallery("03-miss-vitoriabeatrizslv-403-likes-4-fotos-DSYyoSojTWp/miss-trabalho-03-foto-02-DSYyoSojTWp.jpg", "03-miss-vitoriabeatrizslv-403-likes-4-fotos-DSYyoSojTWp/miss-trabalho-03-foto-01-DSYyoSojTWp.jpg"),
      backgroundImage: dressImage("03-miss-vitoriabeatrizslv-403-likes-4-fotos-DSYyoSojTWp/miss-trabalho-03-foto-02-DSYyoSojTWp.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss para palco",
    },
    {
      id: "miss-vitoria-beatriz-394",
      collectionId: "miss",
      title: "Top faixa gala",
      eyebrow: "Faixa",
      shortDescription: "Look de faixa com impacto de concurso e leitura de vencedora.",
      detailDescription: "As duas fotos entram como prova visual de palco e completam o album de Miss com uma direcao clara para concursos.",
      idealFor: ["Miss", "Faixa", "Top", "Concurso"],
      visualDetails: ["Leitura de vencedora", "Gala de concurso", "Imagem vertical", "Presenca sob luz"],
      gallery: makeGallery("04-miss-vitoriabeatrizslv-394-likes-4-fotos-DSbB02NErhf/miss-trabalho-04-foto-01-DSbB02NErhf.jpg", "04-miss-vitoriabeatrizslv-394-likes-4-fotos-DSbB02NErhf/miss-trabalho-04-foto-02-DSbB02NErhf.jpg"),
      backgroundImage: dressImage("04-miss-vitoriabeatrizslv-394-likes-4-fotos-DSbB02NErhf/miss-trabalho-04-foto-01-DSbB02NErhf.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss com faixa",
    },
    {
      id: "miss-mariana-barroso",
      collectionId: "miss",
      title: "Palco perolado",
      eyebrow: "Concurso",
      shortDescription: "Referencia complementar de Miss para quem busca gala, pose e palco.",
      detailDescription: "O album organiza mais uma sequencia real do acervo, ampliando a variedade de vestidos de concurso disponiveis para consulta visual.",
      idealFor: ["Miss", "Concurso", "Gala", "Apresentacao"],
      visualDetails: ["Sequencia real", "Postura de gala", "Cena de concurso", "Referencia para atendimento"],
      gallery: makeGallery("05-miss-marianabarrosonn-0-likes-4-fotos-DXpvWL2lsfX/miss-trabalho-05-foto-02-DXpvWL2lsfX.jpg", "05-miss-marianabarrosonn-0-likes-4-fotos-DXpvWL2lsfX/miss-trabalho-05-foto-01-DXpvWL2lsfX.jpg"),
      backgroundImage: dressImage("05-miss-marianabarrosonn-0-likes-4-fotos-DXpvWL2lsfX/miss-trabalho-05-foto-02-DXpvWL2lsfX.jpg"),
      proof: "2 fotos reais do look",
      accent: "var(--violet)",
      imagePosition: "50% 14%",
      mobilePosition: "50% 10%",
      whatsappContext: "vestido de Miss palco perolado",
    },
  ],
  process: [
    ["01", "Diga sua data", "Informe o evento, horario e tipo de vestido que procura."],
    ["02", "Escolha o estilo", "Envie referencias de cor, brilho, volume e caimento."],
    ["03", "Visite sem compromisso", "O atelie orienta opcoes antes da sua decisao."],
    ["04", "Reserve o modelo", "Gostou do vestido? Saia com a data encaminhada."],
  ],
};

clientConfig.dressItems = clientConfig.dressItems.map(applyDressBackgroundProfile);

export function buildReservationUrl(context = "") {
  const message = context
    ? `Ola, Atelier Kaleb Aguiar. Vim pelo site e quero conhecer os vestidos sem compromisso. Tenho interesse em: ${context}.`
    : "Ola, Atelier Kaleb Aguiar. Vim pelo site e quero conhecer os vestidos sem compromisso.";
  return `${clientConfig.whatsappUrl}?text=${encodeURIComponent(message)}`;
}
